### ISSUE TITLE
testopia- python-driver 

### ISSUE THREAD

**Issue by lilinyueyue** [kinow/testopia-java-driver#6]
testopia.TestopiaXmlrpcError: Error while executing cmd 'TestPlan.get(4)' --> <Fault -32601: "The requested method 'TestPlan.get' was not found.">

**Comment by lilinyueyue** [comment]
config.cfg to store the login info:

[testopia]
username: yourusername@greatbaysoftware.com
password: password
url: https://bugzilla.company.co/xmlrpc.cgi

script to call python driver:
#!/usr/bin/python
# -*- coding: utf-8 -*-

from time import sleep
import urllib
import os,sys
import logging
import json
import subprocess
import time
import ConfigParser
import logging
import logging.config


import xmlrpclib,  httplib
from types import *
from datetime import datetime, time

from cookielib import CookieJar

from testopia import Testopia
t = Testopia.from_config('config.cfg')
t.testplan_get(4)


testopia.py is the one driver

**Comment by kinow** [comment]
@lilinyueyue could you explain a bit more the error? Did you use the Java API to talk to the Testopia Perl backend? If so, I assume the Python code is just an example of a similar client?

**Comment by lilinyueyue** [comment]
Hi, thanks for the quick reply.
Here are the more details:
**Goal:** 
To run my python script to invoke python driver called "testopia.py " under the directory "/usr/local/www/bugzilla/extensions/Testopia/contrib/drivers/python/", then login to bugzilla/testopia server to get the tests information for my automation, then to update the test results based on the test automation runs.

**Version info:**
Apache24:
Perl: 5
bugzilla: 44.12
Testopia: 2.5
python2.7

Steps:
1. python script calls the testopia.py which with calling the config.cfg file. the config.cfg has login info: username, password and url
2. testopia.py calles the xmlrpc via xmlrpc.cgi.
2.1 the login is successful as I can see python output.
2.2. failed on finding the method Testplan.get or any get method.
here is more detail output: I keep login info changed.

Note: there are two things I used work around
1. There was get reply bug, I used work around. 
2. I also used work around to by pass the ssl verification. 

$ python2 mytest.py
self.server.User.login({'login': ‘me@mycompany.com', 'password': ‘my password’})
send: "POST /xmlrpc.cgi HTTP/1.1\r\nHost: servername.dnsname\r\nAccept-Encoding: gzip\r\nUser-Agent: xmlrpclib.py/1.0.1 (by www.pythonware.com)\r\nContent-Type: text/xml\r\nContent-Length: 331\r\n\r\n<?xml version='1.0'?>\n<methodCall>\n<methodName>User.login</methodName>\n<params>\n<param>\n<value><struct>\n<member>\n<name>login</name>\n<value><string>llin@greatbaysoftware.com</string></value>\n</member>\n<member>\n<name>password</name>\n<value><string>my password</string></value>\n</member>\n</struct></value>\n</param>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 27 Feb 2018 03:28:33 GMT
header: Server: Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2l mpm-itk/2.4.7-04 mod_perl/2.0.10 Perl/v5.24.3
header: SOAPServer: SOAP::Lite/Perl/1.26
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Xss-Protection: 1; mode=block
header: Content-Length: 273
header: Content-Type: text/xml
================
h=<httplib.HTTPSConnection instance at 0x109d54098>
================
body: '<?xml version="1.0" encoding="UTF-8"?><methodResponse><params><param><value><struct><member><name>token</name><value><string>1-4FrADC0OuH</string></value></member><member><name>id</name><value><int>1</int></value></member></struct></value></param></params></methodResponse>'
self.server.TestPlan.get(4)
send: "POST /xmlrpc.cgi HTTP/1.1\r\nHost: servername.dnsname\r\nAccept-Encoding: gzip\r\nUser-Agent: xmlrpclib.py/1.0.1 (by www.pythonware.com)\r\nContent-Type: text/xml\r\nContent-Length: 151\r\n\r\n<?xml version='1.0'?>\n<methodCall>\n<methodName>TestPlan.get</methodName>\n<params>\n<param>\n<value><int>4</int></value>\n</param>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 27 Feb 2018 03:28:37 GMT
header: Server: Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2l mpm-itk/2.4.7-04 mod_perl/2.0.10 Perl/v5.24.3
header: SOAPServer: SOAP::Lite/Perl/1.26
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Xss-Protection: 1; mode=block
header: Set-Cookie: Bugzilla_login_request_cookie=kSzeyHJZZK; path=/; HttpOnly
header: Content-Length: 312
header: Content-Type: text/xml
================
h=<httplib.HTTPSConnection instance at 0x109d54098>
================
body: '<?xml version="1.0" encoding="UTF-8"?><methodResponse><fault><value><struct><member><name>faultString</name><value><string>The requested method \'TestPlan.get\' was not found.</string></value></member><member><name>faultCode</name><value><int>-32601</int></value></member></struct></value></fault></methodResponse>'
Traceback (most recent call last):
  File "mytest.py", line 26, in <module>
    t.testplan_get(4)
  File "/Users/Admin/testopia14/testopia.py", line 784, in testplan_get
    return self.do_command("TestPlan.get", [self._number_noop(plan_id)])
  File "/Users/Admin/testopia14/testopia.py", line 510, in do_command
    raise TestopiaXmlrpcError(verb, params, e)
testopia.TestopiaXmlrpcError: Error while executing cmd 'TestPlan.get(4)' --> <Fault -32601: "The requested method 'TestPlan.get' was not found.">

**Comment by lilinyueyue** [comment]
@kinow, to answer your question:
I used python client to call  testopia interface (or python driver :Testopia.py ) to talk to Testopia Perl backend. yes, the Python code is just an example of a similar client.

**Comment by kinow** [comment]
Oh, got it. Thanks for the explanation @lilinyueyue . Unfortunately I can't really help with that. This repository is just for the Java API client. I think I used the Python API in the beginning when trying the API for the first time, but it is maintained by the same developers from Bugzilla/Testopia. You would have to report the issue there to get someone to look into that 👍

**Comment by lilinyueyue** [comment]
@kinow from some other posts I learned that why the login has no issue is because user.log is a perl method, but TestPlan.get is a python method, unless the method Userlogin is ported to be a python method, this way the TestPlan.get will be found after the Userlogin. not really understood this but test I saw is the login is indeed work, but not the TestPlan. get method. hopefully you will have some ideas. here is the link I have beed looked 
https://bug423637.bmoattachments.org/attachment.cgi?id=326546

**Comment by kinow** [comment]
Not really sure how to help. This repository is only for the Java client, for the old Perl API. Not related to the Python examples or another Python library... I remember having issues before with login when they started changing the way they handle Cookies in the requests, but that's about the time I started working on other projects, and didn't have much time to maintain the Java API.

**Comment by kinow** [comment]
You probably have to look for bugs here: https://bugzilla.mozilla.org, and use the right filter/category for Testopia. If no issues related to your problem, you can report one there.

**Comment by lilinyueyue** [comment]
I linked my issue in git there  https://bugzilla.mozilla.org, it looks like there is no public repository.  if you know someone else good at python testopia driver, please recommend. Thanks.
